apiVersion: apps/v1
kind: Deployment
metadata:
  name: komodor-oomkilled
  namespace: default
  labels:
    app: komodor-oomkilled
spec:
  replicas: 3
  selector:
    matchLabels:
      app: komodor-oomkilled
  template:
    metadata:
      labels:
        app: komodor-oomkilled
    spec:
      containers:
      - name: komodor-oomkilled
        image: polinux/stress
        command: ["stress"]
        args: ["--vm", "10", "--vm-bytes", "100M", "--vm-hang", "120", "--backoff", "10000000", "--verbose"]
        resources:
          requests:
            memory: "120Mi"
          limits:
            memory: "120Mi"
