apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: komo-application-error
    app.komodor.com/app: https://github.com/komodorio-demo/inventory-manager
    app.komodor.com/app.ref: 1a9cade740c6baf090f027d8e16747c5c9add55f
  labels:
    app: komo-application-error
  name: komo-application-error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komo-application-error
  template:
    metadata:
      labels:
        app: komo-application-error
    spec:
      containers:
      - env:
        image: us-central1-docker.pkg.dev/komodor-load-test/workshop-image-repository/app:1.3.201
        name: python
