apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app: komo-application-error-step2
    app.komodor.com/app: https://github.com/komodorio-demo/inventory-manager
    app.komodor.com/app.ref: aa32954452b4b5fad1211711395dea3a5d33ca2f
  labels:
    app: komo-application-error
  name: komo-application-error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komo-application-error
  template:
    metadata:
      labels:
        app: komo-application-error
      annotations:
        app: komo-application-error-step2
    spec:
      containers:
      - env:
        image: us-central1-docker.pkg.dev/komodor-load-test/workshop-image-repository/app:1.3.202
        name: python
